### ISSUE TITLE
Improve Bio

### ISSUE THREAD

**Issue by wimpywarlord** [avats101/avats101#1]
Try this out: https://github.com/vinnovateit/Github_readme_template
Also :  https://github.com/anuraghazra/github-readme-stats

**Comment by avats101** [comment]
Thanks @wimpywarlord for this resource.Its actually so nice of you to help others help Improve.I will surely look into it and make changes!

**Comment by avats101** [comment]
You can have a look at it now.I have made my best efforts to make it upto date.

**Comment by wimpywarlord** [comment]
amazing 🌊
